version = 1

[[analyzers]]
name = "javascript"
enabled = true
source = "Frontend_Web"

[[analyzers]]
name = "javascript"
enabled = true
source = "Backend"

[[analyzers]]
name = "javascript"
enabled = true
source = "Frontend_Mobile"
